# Generated by Django 5.0.6 on 2024-07-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=128, verbose_name="Наименование категории"
                    ),
                ),
                (
                    "category_description",
                    models.TextField(max_length=255, verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["-category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=128, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "product_description",
                    models.TextField(max_length=255, verbose_name="Описание продукта"),
                ),
                (
                    "product_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalog/photo",
                        verbose_name="Изображение продукта",
                    ),
                ),
                (
                    "product_cost",
                    models.ImageField(upload_to="", verbose_name="Цена за покупку"),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "upload_at",
                    models.DateTimeField(verbose_name="Дата последнего изменения"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="catalog.category",
                        verbose_name="Название категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["-product_name"],
            },
        ),
    ]
