# Generated by Django 5.0.6 on 2024-07-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_cost",
            field=models.IntegerField(verbose_name="Цена за покупку"),
        ),
    ]
