# Generated by Django 5.0.6 on 2024-07-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_post"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[],
        ),
    ]
