# Generated by Django 5.0.6 on 2024-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(null=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="upload_at",
            field=models.DateTimeField(
                null=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
